{% set version = "2.10" %}
{% set name = "illumiprocessor" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  build:
    - python {{ python }}
    - pip
  run:
    - python
    - trimmomatic 0.39
    - openjdk 11.0.8

test:
  imports:
    - illumiprocessor
  commands:
    - illumiprocessor --help

about:
  home: https://github.com/faircloth-lab/illumiprocessor
  summary: illumiprocessor is a tool to batch process illumina sequencing reads using the excellent trimmomatic package.
  license: BSD
  license_file: LICENSE.txt
