# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # If we set the default shell here, it catches the activated conda
    # and we don't need to keep calling it.
    defaults:
      run:
        shell: bash -l {0}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          auto-update-conda: true
          python-version: 3.6
          channels: conda-forge, bioconda
      - name: Install dependencies using conda
        run: conda install trimmomatic=0.39 openjdk=11.0.8 pytest=6.2.2
      - name: Check Package Installation
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
      - name: Update PYTHONPATH
        run: |
          echo "$GITHUB_WORKSPACE/" >> $GITHUB_PATH
      - name: Run pytest
        run: |
          pytest -vv